catalog/urls.py
from django.urls import path

from . import views

# URLs basics (this do not need to authencitcate)
urlpatterns = [
    path('', views.index, name='index'),

    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>/', views.BookDetailView.as_view(), name='book-detail'),

    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>/', views.AuthorDetailView.as_view(), name='author-detail'),
]

# URLs for library members
urlpatterns += [
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
]

# URLs for librerian and superusers
urlpatterns += [
    path('loanedbooks/', views.LoanedBooksListView.as_view(), name='loaned-books'),
    path('book/<str:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
    path('book/create/', views.BookCreate.as_view(), name='book-create'),
    path('book/<int:pk>/update/', views.BookUpdate.as_view(), name='book-update'),
    path('book/<int:pk>/delete/', views.BookDelete.as_view(), name='book-delete'),

    path('author/create/', views.AuthorCreate.as_view(), name='author-create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author-update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author-delete'),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
]

#Add URL maps to redirect the base URL to our application
urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
]

#Use static() to add url mapping to serve static files during development (only)as

# Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

catalog/models.py
from django.db import models
from django.urls import reverse #Used to generate URLs by reversing the URL patterns
from django.contrib.auth.models import User

from datetime import date

import uuid # Requerida para las instancias de libros únicos.

class Genre(models.Model):
    """
    Modelo que representa un género literario (p. ej. ciencia ficción, poesía, etc.).
    """

    name = models.CharField(max_length=200, help_text="Ingrese el nombre del género (p. ej. Ciencia Ficción, Poesía Francesa, etc.).")

    def __str__(self):
        """
        Cadena que representa a la instancia particular del modelo (p. ej. en el sitio de administración).
        """
        return self.name

class Language(models.Model):
    """
    Modelo que representa un lenguaje (p. ej. Inglés, Español, Japones, etc.).
    """

    name = models.CharField(max_length=200, help_text="Ingrese el lenguaje del libro (p. ej. Inglés, Español, Japones. etc.)")

    def __str__(self):
        """
        String para representar el Modelo Objeto.
        """
        return self.name

class Book(models.Model):
    """
    Modelo que representa un libro (pero no un Ejemplar específico).
    """

    title = models.CharField(max_length=200)

    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    #ForeignKey, ya que un libro tiene un solo autor, pero el mismo autor puede haber escrito muchos libros.
    #'Author' es un string, en ves de un objeto, porque la clase Author aún no ha sido declarada.

    summary = models.TextField(max_length=1000, help_text="Ingrese una breve descripción del libro")

    isbn = models.CharField('ISBN', max_length=13, help_text="13 Caracteres <a href='https://www.isbn-international.org/content/what-isbn' target='_blank'>ISBN number</a>")

    genre = models.ManyToManyField(Genre, help_text="Seleccione un genero para este libro")
    #ManyToManyField, porque un género puede tener muchos libros y un libro puede cubrir varios géneros.
    #La clase Genre ya ha sido definida, entonces podemos especificar el objeto arriba.

    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        """
        String que representa al objeto Book
        """
        return self.title

    def get_absolute_url(self):
        """
        Devuelve el URL a una instancia particular de Book
        """
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        """
        Crea un String para el género. Esto es requerido para mostrar el género en Admin.
        """
        return ', '.join([genre.name for genre in self.genre.all()[:3] ])
    display_genre.short_description = 'Genre'


class BookInstance(models.Model):
    """
    Modelo que representa una copia específica de un libro (i.e. que puede ser prestado por la biblioteca).
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="ID único para este lirbo particular en la biblioteca")
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text="Disponibilidad del lirbo")

    class Meta:
        ordering = ["due_back"]
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        """
        String para representar el Objeto del Modelo.
        """
        return '%s (%s)' % (self.id, self.book.title)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

class Author(models.Model):
    """
    Modelo que representa un autor.
    """

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    def get_absolute_url(self):
        """
        Retorna la url para acceder a una instancia particular de un autor.
        """
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """
        String para representar el Objeto Modelo.
        """
        return '%s, %s' % (self.last_name, self.first_name)

catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

import datetime #for checking renewal date range

class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Ingresa una fecha entre hoy y 4 semanas (Predeterminada 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        #Check date is not in past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        #Check date is in range librarian allowed to change (+4 weeks).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        #Remember to always return the cleaned cleaned data
        return data

catalog/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .models import Book, Author, BookInstance, Genre
from .forms import RenewBookForm

import datetime

def index(request):
    """
    Función vista para la página inicio del sitio.
    """
    # Genera contadores de algunos de los objetos principales
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    # Libros disponibles (status = 'a')
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    num_authors = Author.objects.count() # El 'all()' está implicito por defecto

    genre_count = {}
    for genre in Genre.objects.all():
        num_book_genre = Book.objects.filter(genre__exact=genre).count()
        genre_count[genre]=num_book_genre

    # Numero de visitas para esta vista, como conteo en la variable de session.
    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits + 1

    _context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'genre_count': genre_count,
        'num_visits': num_visits
    }

    # Renderiza la plantilla HTML index.html con los datos en la variable contexto
    return render(request, 'catalog/index.html', context=_context)

@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request, pk):
    """
    View function for renewing a specific BookInstance by librarian.
    """
    book_inst = get_object_or_404(BookInstance, pk=pk)

    #if this is a POST request then process the Form data
    if request.method == 'POST':
        # Create a form instance and populate it with from the request (binding):
        form = RenewBookForm(request.POST)
        # Check if the form is valid:
        if form.is_valid():
            #Process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            book_inst.due_back = form.cleaned_data['renewal_date']
            book_inst.save()

            #Redirect to a new URL:
            return redirect('loaned-books')
    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

    return render(request, 'catalog/book_renew_librarian.html', context={'form': form, 'bookinst': book_inst})

class BookListView(generic.ListView):
    model = Book
    paginate_by = 10

class BookDetailView(generic.DetailView):
    model = Book

class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 20

class AuthorDetailView(generic.DetailView):
    model = Author

class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """
    Generic class-based view listing books on loan to current user.
    """
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')

class LoanedBooksListView(PermissionRequiredMixin, generic.ListView):
    """
    Generic class-based view listing book on loan to users.
    """
    permission_required = 'catalog.can_mark_returned'
    model = BookInstance
    template_name = 'catalog/loaned_books.html'
    paginate_by = 10

class AuthorCreate(PermissionRequiredMixin, CreateView):
    model = Author
    fields = '__all__'
    initial = {'date_of_death': '05/01/2018'}
    template_name = 'catalog/create_change_form.html'
    permission_required = 'catalog.can_add_author'
    extra_context = {
        'title_window': 'Nuevo autor',
        'title_page': 'Agragar autor',
    }

class AuthorUpdate(PermissionRequiredMixin, UpdateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    template_name = 'catalog/create_change_form.html'
    permission_required = 'catalog.change_author'
    extra_context = {
        'title_window': 'Editar autor',
        'title_page': 'Editar autor',
    }

class AuthorDelete(PermissionRequiredMixin, DeleteView):
    model = Author
    success_url = reverse_lazy('authors')
    template_name = 'catalog/confirm_delete.html'
    permission_required = 'catalog.delete_author'
    extra_context = {
        'title_window': 'Eliminar autor',
        'title_page': 'Eliminar autor',
        'confirm_message': 'Está seguro que desea eliminar al autor',#sin signos, la plantilla los incluirá
    }

class BookCreate(PermissionRequiredMixin, CreateView):
    model = Book
    fields = '__all__'
    template_name = 'catalog/create_change_form.html'
    permission_required = 'catalog.add_book'
    extra_context = {
        'title_window': 'Nuevo libro',
        'title_page': 'Agragar libro',
    }

class BookUpdate(PermissionRequiredMixin, UpdateView):
    model = Book
    fields = '__all__'
    template_name = 'catalog/create_change_form.html'
    permission_required = 'catalog.change_book'
    extra_context = {
        'title_window': 'Editar libro',
        'title_page': 'Editar lirbo',
    }

class BookDelete(PermissionRequiredMixin, DeleteView):
    model = Book
    success_url = reverse_lazy('books')
    template_name = 'catalog/confirm_delete.html'
    permission_required = 'catalog.delete_book'
    extra_context = {
        'title_window': 'Eliminar libro',
        'title_page': 'Eliniar libro',
        'confirm_message': 'Está seguro que desea eliminar el libro',
    }

catalog/templates/catalog/author_detail.html
{% extends 'catalog/base_generic.html' %}

{% block title %}{{ author }} - LocalLibrary{% endblock %}

{% block content %}
<h1>Autor: {{ author }}</h1>

{% if author.date_of_birth and author.date_of_death %}
<span>{{ author.date_of_birth }} - {{ author.date_of_death }}</span>
{% endif %}

{% if perms.catalog.delete_author and perms.catalog.change_author %}
<ul class="nav justify-content-end">
  <li class="nav-item">
    <a href="{{ author.get_absolute_url }}" class="nav-link text-danger mr-2">Eliminar</a>
  </li>
  <li class="nav-item">
    <a href="{{ author.get_absolute_url }}" class="nav-link btn-secondary rounded">Editar</a>
  </li>
</ul>
{% endif %}

<div style="margin-left:20px;">
  <h3>Libros</h3>
  {% for book in author.book_set.all %}
  <div>
    <a href="{{ book.get_absolute_url }}">{{ book }}</a> <strong>({{ book.bookinstance_set.all.count }})</strong>
    <p>{{ book.summary }}</p>
  </div>
  {% endfor %}
</div>

{% endblock %}

catalog/templates/catalog/author_list.html
{% extends 'catalog/base_generic.html' %}

{% block title %}Autores - Locallibrary{% endblock %}

{% block content %}
<h1>Autores</h1>
{% if perms.catalog.can_add_author %}
<ul class="nav justify-content-end">
  <li class="nav-intem">
    <a href="{% url 'author-create' %}" class="nav-link btn-secondary rounded">Nuevo autor</a>
  </li>
</ul>
{% endif %}
<ul>
  {% for author in author_list %}
  <li><a href="{{ author.get_absolute_url }}">
    {{ author }}
    {% if author.date_of_birth and author.date_of_death %}
    ({{ author.date_of_birth }} - {{ author.date_of_death }})
    {% endif %}
  </a></li>
  {% endfor %}
</ul>
{% endblock %}

catalog/templates/catalog/base_generic.html
<!DOCTYPE html>
<html lang="es" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="manifest" href="{% static 'json/manifest.json' %}">

    <title>{% block title %}Locallibrary{% endblock %}</title>
  </head>
  <body>

    <div class="container-fluid">

      <div class="row">
        <div class="col-sm-2">
          {% block sidebar %}
          <ul class="sidebar-nav">
            <li><a href="{% url 'index' %}">Inicio</a></li>
            <li><a href="{% url 'books' %}">Libros</a></li>
            <li><a href="{% url 'authors' %}">Autores</a></li>
            <hr>
            {% if user.is_authenticated %}
            <li>Usuario: {{ user.get_username }}</li>
            {% if perms.catalog.can_mark_returned %}
              <li><a href="{% url 'loaned-books' %}">Libros prestados</a></li>
            {% else %}
              <li><a href="{% url 'my-borrowed' %}">Mis libros prestados</a></li>
            {% endif %}
            <hr>
            <li><a href="{% url 'logout' %}">Cerrar sesión</a></li>
            {% else %}
            <li><a href="{% url 'login' %}">Iniciar sesión</a></li>
            {% endif %}
          </ul>
          {% endblock %}
        </div>
        <div class="col-sm-10">
          {% block content %}{% endblock %}

          {% block pagination %}
            {% if is_paginated %}
            <div class="pagination">
              <span class="page-links">
                {% if page_obj.has_previous %}
                <a href="{{ request.paht }}?page={{ page_obj.previous_page_number }}">Anterior</a>
                {% endif %}
                <span class="page-current">
                  Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">Siguiente</a>
                {% endif %}
              </span>
            </div>
            {% endif %}
          {% endblock %}
        </div>
      </div>

    </div>
  </body>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</html>

catalog/templates/catalog/book_detail.html
{% extends 'catalog/base_generic.html' %}

{% block title %}{{ book.title }} - LocalLibrary{% endblock %}

{% block content %}
<h1>Titulo: {{ book.title }}</h1>

{% if perms.catalog.change_book and perms.catalog.delete_book %}
<ul class="nav justify-content-end">
  <li class="nav-item">
    <a href="{{ book.get_absolute_url }} " class="nav-link text-danger mr-2">Eliminar</a>
  </li>
  <li class="nav-item">
    <a href="{{ book.get_absolute_url }}" class="nav-link btn-secondary rounded">Editar</a>
  </li>
</ul>
{% endif %}

<p><strong>Autor:</strong><a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a></p>
<p><strong>Resumen:</strong> {{ book.summary }}</p>
<p><strong>ISBN:</strong> {{ book.isbn }}</p>
<p><strong>Idioma:</strong> {{ book.language }}</p>
<p>
  <strong>Género:</strong>
  {% for genre in book.genre.all %}
  {{ genre }}
  {% if not forloop.last %},{% endif %}
  {% endfor %}
</p>

<div style="margin-left:20px;margin-top:20px;">
  <h4>Copias</h4>
  {% for copy in book.bookinstance_set.all %}
  <hr>
  <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
  {% if copy.status != 'a' %}
  <p><strong>Fecha de devolución:</strong> {{ copy.due_back }}</p>
  {% endif %}
  <p><strong>Ipresion:</strong> {{ copy.imprint }}</p>
  <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
  {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends 'catalog/base_generic.html' %}

{% block title %}Libros - LocalLibrary{% endblock %}

{% block content %}
<h1>Lista de libros</h1>

{% if perms.catalog.add_book %}
<ul class="nav justify-content-end">
  <li class="nav-item"><a href="{% url 'book-create' %}" class="nav-link btn-secondary rounded">Nuevo libro</a></li>
</ul>
{% endif %}

{% if book_list %}
<ul>

  {% for book in book_list %}
  <li>
    <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{ book.author }})
  </li>
  {% endfor %}

</ul>
{% else %}
<p>La libreria está vacia</p>
{% endif %}

{% endblock %}

catalog/templates/catalog/book_renew_librarian.html
{% extends 'catalog/base_generic.html' %}

{% block title %}Renovar libro - Locallibrary{% endblock %}

{% block content %}
<h1>Renovar: {{ bookinst.book }}</h1>
<p>Prestatario: {{ bookinst.borrower }}</p>
<p {% if bookinst.is_overdue %}class="text-danger"{% endif %}>Fecha de retorno: {{ bookinst.due_back }}</p>

<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form }}
  </table>
  <input type="submit" value="Enviar">
</form>
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends 'catalog/base_generic.html' %}

{% block title %}Mis libros - LocalLibrary{% endblock %}

{% block content %}
<h1>Libros prestados</h1>

{% if bookinstance_list %}
<ul>
  {% for bookinst in bookinstance_list %}
  <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
    <a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a> ({{ bookinst.due_back }})
  </li>
  {% endfor %}
</ul>
{% else %}
<p>No tienes libros prestados.</p>
{% endif %}
{% endblock %}

catalog/templates/catalog/confirm_delete.html
{% extends 'catalog/base_generic.html' %}

{% block title %}{{ title_window }} - LocalLibrary{% endblock %}

{% block content %}

<h1>{{ title_page }}</h1>

<p>¿{{ confirm_message }}: {{ object }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Sí, borrar." />
</form>

{% endblock %}

catalog/templates/catalog/create_change_form.html
{% extends 'catalog/base_generic.html' %}

{% block title %}{{ title_window }} - LocalLibrary{% endblock %}

{% block content %}
<h1>{{ title_page }}</h1>
<form class="" action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Enviar">
</form>
{% endblock %}

catalog/templates/catalog/index.html
{% extends 'catalog/base_generic.html' %}

{% block title %}
Inicio - LocalLibrary
{% endblock %}

{% block content %}
<h1>Iniciio libreria local</h1>

<p>Bienvenido a <em>LocalLibrary</em>, un sitio web muy básico de Django desarrollado como un ejemplo tutorial en la red de desarrolladores de Mozilla.</p>

<h2>Contenido dinámico</h2>
<p>La biblioteca tiene los siguientes recuentos de registros:</p>
<ul>
  <li><strong>Libros:</strong> {{ num_books }}</li>
  <li><strong>Copias:</strong> {{ num_instances }}</li>
  <li><strong>Copias disponibles:</strong> {{ num_instances_available }}</li>
  <li><strong>Autores:</strong> {{ num_authors }}</li>
  <li>
    <strong>Géneros:</strong>
    <ul>
      {% for genre, total in genre_count.items %}
      <li><strong>{{ genre }}:</strong> {{ total }}</li>
      {% endfor %}
    </ul>
  </li>
</ul>
<p>Tu has visitado esta página {{ num_visits }} ve{{ num_visits|pluralize:'z,ces' }}</p>
{% endblock %}

catalog/templates/catalog/loaned_books.html
{% extends 'catalog/base_generic.html' %}

{% block title %}Libros prestados - Locallibrary{% endblock %}

{% block content %}
<h1>Libros prestados</h1>
<ul>
  {% for bookinst in bookinstance_list %}
  <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
    <a href="{{ bookinst.book.get_absolute_url }}">{{ bookinst.book }}</a>
    ({{ bookinst.due_back }}) - {{ bookinst.borrower }}
    {% if perms.catalog.can_mark_returned %} - <a href="{% url 'renew-book-librarian' bookinst.id %}">Renovar</a>{% endif %}
  </li>
  {% endfor %}
</ul>
{% endblock %}